In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.shape

(404290, 6)

In [4]:
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [5]:
new_df = df.sample(30000)

In [6]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [7]:
new_df.duplicated().sum()

np.int64(0)

In [8]:
ques_df = new_df[['question1','question2']]

In [9]:
ques_df.head()

,question1,question2
297263,Who is the ideal wife from your (a male) point...,"What are your expectations of marriage, from a..."
95167,Should I tell my ex-girlfriend I cheated?,Should I hate my ex-girlfriend for cheating on...
21810,How do I get that peace of mind?,How do I have peace of mind?
13370,What is generally played with the left hand w...,How can I increase the independence of my left...
53416,What is the price per watt of laser over time?,Is canteens price same all over the country?

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
questions = list(ques_df['question1']) + list(ques_df['question2'])

In [11]:
cv = CountVectorizer(max_features=3000)

In [12]:
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [13]:
temp_df1 = pd.DataFrame(q1_arr, index=ques_df.index)
temp_df2 = pd.DataFrame(q1_arr, index=ques_df.index)
temp_df = pd.concat([temp_df1,temp_df2], axis=1)
temp_df.shape

(30000, 6000)

In [17]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
297263,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
95167,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21810,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53416,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102672,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
362793,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
385687,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
359040,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
temp_df['is_duplicate'] = new_df['is_duplicate']

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,
                                                    test_size=0.2, random_state=42)

In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7166666666666667